### ISSUE TITLE
Project Proposal Feedback

### ISSUE THREAD

**Issue by PhilChodrow** [jeff1hwang/PIC16B_Diabetes_Prediction_Project#1]
Hi Yiran, Jiyuan, and Zhuofan, 

I think this is an excellent project proposal! It is very close to receiving credit. I would like you to add two items: 

1. Please give me some scenarios for "full success" and "partial success" of your project. I think you have mostly described the "full success" scenario, so mainly I want you to tell me about the "partial success" scenario. If you find yourselves short of time or struggling to complete some of the tasks, what a simpler product that you will create that still offers something valuable to the user? 
2. Regarding the ethics section, please comment on a few things you might do in your project to guard against some of the risks you described. I am particularly interested in how you propose to address the important risk of false negatives, which could lead to very bad health consequences. 

Please attend to these revisions and then comment on this issue thread. I'll review your revised proposal and assess it for credit. 

I look forward to seeing what you create!

**Comment by jeff1hwang** [comment]
Dear Professor,

Thank you for pointing out the above items!

1. Scenarios for "full success" and "partial success":
 - **Full Success:**

Our goal for "Full Success" is to create a Web Page - Diabetes Risk Test. This Web Page will be based on the machine learning model that we’ll train using the [Early-stage diabetes risk prediction dataset](https://archive.ics.uci.edu/ml/datasets/Early+stage+diabetes+risk+prediction+dataset.#) from UCI Machine Learning Repository. Our Web App interface will generate a list of questions. These questions may relate to respondents’ age, gender, and current symptoms. After the respondent completes the risk test, the Web App will determine whether the respondent is potentially at risk for diabetes based on a pre-trained model. If the model determines that the respondent is potentially at risk for diabetes, we will recommend the respondent to go to the hospital for a more comprehensive examination as soon as possible.

- **Partial Success:**

In our project, our goal for Partial Success is to find the appropriate machine learning algorithm to complete the training of the dataset and get a model with a prediction accuracy of at least 95%. This "Partial Success" will be based on the condition that we are unable to complete the Web App on time. The reasons for not being able to complete the Web App may be 1. lack of time, or 2. insufficient knowledge to support an interactive Web App interface. In this case, our product will be the accurate model that we train using the data set. We will introduce and share our model with doctors, hospitals, and medical practitioners.


2. Regarding the ethics section, we would do the following to avoid some issues:

False-negative issue: before the respondent starts filling out the Test, we will inform the respondent of the possibility that the test could be inaccurate by popping up a window on the web page. We would also highlight the possibility of false-negative test results, and even if the results are negative, we strongly recommend that patients go to the hospital for a professional physical examination in case of any abnormal physical conditions. (Early symptoms of diabetes vary from person to person and may be different for each individual, so it is highly recommended that anyone who feels abnormal go to the hospital immediately for a more specialized examination)


We've also added the above items into the README.MD file. Thank you!

Sincerely,
Zhuofan

**Comment by PhilChodrow** [comment]
I see! These look like good revisions. 

While checking that you had indeed incorporated these revisions into your proposal, I noticed that there is a technical specification that you haven't yet met. Specification 2 on the assignment reads: 

> "Each team member has made at least two commits to this file, which in total demonstrate substantial commitments to the writing of the proposal."

In your commit history, I see only commits by @jeff1hwang. Please consult in your group, suggest some improvements to the proposal, and have these improvements be written and committed by @JiyuanLyu and @yiranelmo. 

I assume that @JiyuanLyu and @yiranelmo have already made contributions to the text. However, I am requiring you to also commit this so that (a) there is no question about this and (b) you get practice using collaborative workflows. 

Let me know once you've done this and I'll re-assess.

**Comment by jeff1hwang** [comment]
Dear Professor,

Thank you for your reply! 

My teammates @JiyuanLyu @yiranelmo have made at least two commits to the file now. 

Because my team previously wrote the project proposal on Google Docs, my teammates' improvements to the proposal were not committed to Github. We will definitely commit all our future teamwork to GitHub.

Best Regards,
Zhuofan

**Comment by PhilChodrow** [comment]
Understood, that's kind of what I had expected. As is, these aren't very substantial commits with regards to the proposal content, but they do show use of the collaborative workflow. Please make sure that your commits in the remainder of the project reflect a transparent and equitable division of labor. I have logged credit for your project proposal. Excited to see the final product!
